/* 
HACKERRANK
MYSQL QUERY TO GET UNIQUE LIST OF ACTIVITES THAT LIE BETWEEN THE MIN AND MAX NUMBER OF PARTICIPANTS
*/

/*
SOLUTION 1 : USING BOTH ACTIVITIES AND FRIENDS TABLE
*/

WITH FIRST_DATA AS (
    SELECT
    ACTIVITY,
    COUNT(*) AS RECORD_COUNT
    FROM FRIENDS
    GROUP BY 1
) 
SELECT
NAME 
FROM ACTIVITIES a
INNER JOIN (SELECT 
            ACTIVITY 
            FROM FIRST_DATA 
            WHERE RECORD_COUNT > (SELECT MIN(RECORD_COUNT) FROM FIRST_DATA)
            AND RECORD_COUNT < (SELECT MAX(RECORD_COUNT) FROM FIRST_DATA) ) b
ON a.NAME = b.ACTIVITY;

/*
SOLUTION 2 : USING ONLY FRIENDS TABLE
*/

WITH FIRST_DATA AS (
    SELECT
    ACTIVITY,
    COUNT(*) AS RECORD_COUNT
    FROM FRIENDS
    GROUP BY 1
) 
SELECT
ACTIVITY 
FROM FIRST_DATA
WHERE RECORD_COUNT > (SELECT MIN(RECORD_COUNT) FROM FIRST_DATA)
AND RECORD_COUNT < (SELECT MAX(RECORD_COUNT) FROM FIRST_DATA);

