SELECT
F.HEADCOUNT, 
FD.HEADCOUNT AS FD_DEMAND,
F.HOURS,
TE.SEQNUM,
TE.TP_EMP_ID,
E.TP_RESOURCE_NAME,
TRIM(TO_CHAR(TE.TP_QCGUID)) AS TP_QCGUID,
TP.TP_PROJECT_NAME,
TP.PROJECT_ID,
D.DAY_DATE
,LEFT(TO_CHAR(D.FISCAL_YEAR_MONTH_NAME),4)||'-'||RIGHT(TRIM(TO_CHAR(D.FISCAL_YEAR_MONTH_NAME)), -2) AS "FISCAL_MONTH"
,CASE WHEN D.DAY_DATE <= TRUN(LAST_DAY(ADD_MONTHS(CURRENT_DATE,-2))+1) THEN 
LEFT(TO_CHAR(D.FISCAL_YEAR_MONTH_NAME),4)||'-'||RIGHT(TRIM(TO_CHAR(D.FISCAL_YEAR_MONTH_NAME)),2) ELSE
MAX(CASE WHEN D.DAY_DATE = TRUN(LAST_DAY(ADD_MONTHS(CURRENT_DATE,-2))+1)THEN LEFT(TO_CHAR(D.FISCAL_YEAR_MONTH_NAME),4)||'-'||RIGHT(TRIM(TO_CHAR(D.FISCAL_YEAR_MONTH_NAME)),2) END) OVER (ORDER BY D.DAY_DATE) END AS "FISCALJOIN"
FROM (SELECT * 
      FROM FCT_TEMPUS_FORECAST 
      WHERE CURRENT_FLAG = 1) F
LEFT OUTER JOIN (SELECT * 
                FROM DIM_TEMPUS_PROJECT
                WHERE PROJECT_ORG ='EngIT') TP
ON F.PROJECT_KEY = TP.PROJECT_KEY
LEFT OUTER JOIN DIM_QCT_DHW_EMPLOYEE TE
ON F.EMPLOYEE_KEY = TE.SEQNUM
LEFT OUTER JOIN TEMPUSDW.DIM_DATE D
ON F.HC_MONTH_DATE_KEY = D.DATE_KEY
LEFT OUTER JOIN (SELECT * 
                FROM FCT_TEMPUS_DEMAND 
                WHERE CURRENT_FLAG = 1) FD
ON F.EMPLOYEE_KEY = FD.EMPLOYEE_KEY



